name: Go Version Manager CI

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main

jobs:
  create_tarball:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
